Revert "Removed "Device Options" header from settings menu"
This reverts commit c321678cc90b436ff23b5f5eb4c43cf727d47a6a.

Causes problems elsewhere:
packages/apps/Settings/src/com/android/settings/Settings.java:328: cannot find symbol
symbol  : variable advanced_settings
location: class com.android.settings.R.id
            } else if (id == R.id.advanced_settings) {
                                 ^